version: 2.0

jobs:
  build:
    docker:
      - image: circleci/node:8.5.0

    environment:
       BASH_ENV: ~/.bashrc

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: yarn test
